---
title: "Visualization"
subtitle: "Part 1"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)
```

## Load the weather data

rnoaa lets you access public data online; telling R we want data from these three weather stations. 

Mutate to rename variables for weather station.

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## Scatterplot 

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()
```

New approach, same plot 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax))+
  geom_point()
```

Save and edit plot object 

```{r}
weather_plot = 
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax))

weather_plot + geom_point()
```

## Advnaced scatter plot 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point() + 
  geom_smooth(se = FALSE)
```

What about the `aes` placement?

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name)) +
  geom_smooth()
```

Let's facet some things 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.2) + 
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```

