---
title: "Visualization, Part 2"
output: github_document
---

```{r}
library(tidyverse)
library(patchwork)
```

## Load the weather data


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

Revisit plot for part 1 of session.

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5)
```

## Labels

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) + 
  labs(
  title = "Temp Plot",
  x = "Min Temp",
  y = "Max Temp",
  caption = "data from rnoaa package 2017"
  )
```

## Scales 

X and Y scales 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) + 
  labs(
  title = "Temp Plot",
  x = "Min Temp",
  y = "Max Temp",
  caption = "data from rnoaa package 2017"
  ) +
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15 C", "0", "15 C")
  ) +
  scale_y_continuous(
    position = "right"
  )
```

Color scales 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) + 
  labs(
  title = "Temp Plot",
  x = "Min Temp",
  y = "Max Temp",
  caption = "data from rnoaa package 2017"
  ) +
  viridis::scale_color_viridis(
    name = "location",
        discrete = TRUE)
```

## Themes

Shift the legend

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) + 
  labs(
  title = "Temp Plot",
  x = "Min Temp",
  y = "Max Temp",
  caption = "data from rnoaa package 2017"
  ) +
  viridis::scale_color_viridis(
    name = "location",
        discrete = TRUE) +
  theme(legend.position = "bottom")
```

Change overall theme 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) + 
  labs(
  title = "Temp Plot",
  x = "Min Temp",
  y = "Max Temp",
  caption = "data from rnoaa package 2017"
  ) +
  viridis::scale_color_viridis(
    name = "location",
        discrete = TRUE) + 
  theme_minimal()
```

## Setting options

```{r, eval = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

## Data args in `geom`

```{r}
central_park = 
    weather_df %>% 
  filter(name == "CentralPark_NY")

waik = 
  weather_df %>% 
  filter(name == "Waikiki_HA")

ggplot(data = waik, aes(x = date, y = tmax, color = name))+
  geom_point()+
  geom_line(data = central_park)
```

## Patchwork

Remember faceting?

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, fill = name)) +
  geom_density(alpha = 0.5) +
  facet_grid(. ~ name)
```

what happens when you want multipanel plots but can't facet?

```{r}
tmax_tmin_plot =
  weather_df %>% 
    ggplot(aes(x = tmin, y = tmax, color = name)) +
    geom_point(alpha = 0.5) +
    theme(legend.position = "none")

prcp_dens_plot = 
  weather_df %>% 
  filter(prcp > 0) %>% 
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = 0.5)+
  theme(legend.position = "none")

tmax_dates_plot = 
  weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() + 
  geom_smooth(se = FALSE) +
  theme(legend.position = "none")

(tmax_tmin_plot + prcp_dens_plot) / tmax_dates_plot
```



